export const SET_ACCESS_TOKEN = "AUTH/SET_ACCESS_TOKEN"
export const SET_REFRESH_TOKEN = "AUTH/SET_REFRESH_TOKEN"
export const SET_DATA_USER = "AUTH/SET_DATA_USER"
export const SET_EXP_TOKEN = "AUTH/SET_EXP_TOKEN"
